### ISSUE TITLE
In the Monocart output the folder "webpack:/src" remains empty!

### ISSUE THREAD

**Issue by KHisir** [edumserrano/monocart-code-coverage-demo#3]
Hello eduardo,

First of all, thank you very much for the great solution. I built a simple Angular 15 application and wanted to apply your solution to my application. I adapted everything exactly as in your example application. Everything works great too. Only after running "npm run test-monocart" no files are displayed in the reporter. Your output will list all files under “webpack:/src”. But not for me. Do you have a solution for me? For comparison, here is my output:

![image](https://github.com/edumserrano/monocart-code-coverage-demo/assets/13102380/5786fef7-f48d-412d-90e4-c906628cc226)

**Comment by KHisir** [comment]
...and here is my test application:
[Test Coverage Example.zip](https://github.com/edumserrano/monocart-code-coverage-demo/files/13451306/Test.Coverage.Example.zip)

**Comment by edumserrano** [comment]
Got it working, I can see this now:

![image](https://github.com/edumserrano/monocart-code-coverage-demo/assets/15857357/f2ddba00-fb18-4f2c-87e1-656c83b1e0ca)

What I changed to make it work was:
1) Update to the latest version of the monocart-reporter package by running `npm i monocart-reporter@latest`. That updated the package version to `1.7.13`. 
2) On the `tests\monocart\playwright.config.ts` file replace the following line:
```ts
sourceFilter: (sourceName: any) => sourceName.search(/\/src\//) !== -1,
```
with
```ts
sourceFilter: (sourcePath: string) => sourcePath.search(/src\//u) !== -1,
```

Note that updating the monocart-reporter package might not be necessary but I do recommend it because there's been several updates since the version you have running. The real fix though is the update to the regex being used to filter files out of code coverage on the `sourceFilter` property. The above fix means `include everything that is on the src directory` but you can customize the regex to your liking.
